### ISSUE TITLE
batman-nexthop-monitor not displaying destinations with IEEE 802.11abg Radio Model

### ISSUE THREAD

**Issue by James-Sloop** [adjacentlink/emane-guide#1]
I am currently working through the emane-guide as a new user and I am running into an issue when trying to complete the IEEE 802.11abg Radio Model. I am able to complete the first step, using the "otestpoint-labtools-mtabletool" to subscribe to all "EMANE.IEEE80211abg.Tables.Neighbor" probes which gives a table matching the expected output. The next instruction is to monitor the B.A.T.M.A.N. Next Hop Matrix using "batman-nexthop-monitor.py" which I attempt to do using "~/dev/emane-guide/examples/scripts/batman-nexthop-monitor.py 3" but when the table shows up, it appears to be missing the "*" which should indicate that the final destination is the next hop.

Here is the output I get:
![image](https://github.com/adjacentlink/emane-guide/assets/100043766/8c4e38b9-d026-4f8c-abb2-f651abc1d666)

Here is the expected output:
![image](https://github.com/adjacentlink/emane-guide/assets/100043766/fb939614-e0b7-41eb-9ede-5d7ad8df5627)

Next I am able to instruct the jammer, node-4, to create a continuous tone centered at 2.39GHz with a 20MHz (default) bandwidth, and -20dBm transmit power by using the command "emane-jammer-simple-control -v node-4:45715 on 4 2390000000,-20 -a omni". I was then able to use the "emane-spectrum-analyzer" to view the total and waveform energy which matched the expected graphs. I then used "emanesh node-1 get config nems mac mode unicastrate multicastrate" to check the multicastrate which does match the expected output. The next step is to use the batman-nexthop-monitor again which I do and again I do not get an output matching the expected result.

Here is the output I get:
![image](https://github.com/adjacentlink/emane-guide/assets/100043766/6827ec7f-40fa-4b98-9ecb-098ce99d3d4d)

Here is the expected output:
![image](https://github.com/adjacentlink/emane-guide/assets/100043766/47fb33a0-ae41-42c6-9885-f844f6c98d0f)

I am not sure if it is a problem with EMANE, a problem with my system, a user error, or an issue with the batman-nexthop-monitor script. Any insight would be much appreciated. I am running the examples on an Ubuntu-22_04 local machine using the adjacentlink Pre-built packages.

**Comment by sgalgano** [comment]
Can you ssh onto one of the nodes and verify that `flask-batman-originators-server.py` is running? If not, make sure that you have python3-flask installed.

**Comment by James-Sloop** [comment]
I have confirmed that I have python3-flask installed. How can I check if flask-batman-originators-server.py is running? I am not completely familiar with the emane nodes interface and the bash ps command doesn't work there. Thank you for the quick response.

**Comment by sgalgano** [comment]
You can ssh to one of the lxc nodes (shown below 10.99.0.1) and do a `ps ax`:

```
$ ssh 10.99.0.1
me@node-1:~$ ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 init
     61 ?        Ss     0:00 sshd: /usr/sbin/sshd -o PidFile=/home/me/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/run/ssh.pid [listener] 0 of 10-100 startups
     65 ?        Ssl    0:00 emane emane-platform.xml -r -d -l 3 -f /home/me/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/log/emane.log --pidfile /home/me/dev/emane-guide/examples/ieee
    105 ?        Ssl    0:00 otestpoint-recorder otestpoint-recorder.xml -d -l 3 -f /home/me/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/log/otestpoint-recorder.log --pidfile /home/me
    119 ?        Ssl    0:00 otestpointd otestpoint.xml -r -d -l 3 -f /home/me/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/log/otestpoint.log --pidfile /home/me/dev/emane-guide/exampl
    127 ?        S      0:00 python3 /home/me/dev/emane-guide/examples/ieee80211abg-01/../scripts/flask-batman-originators-server.py
    136 ?        Rl     0:00 otestpoint-probe
    144 ?        Rl     0:00 otestpoint-probe
    152 ?        Sl     0:00 otestpoint-probe
    164 ?        Ss     0:00 sshd: me [priv]
    166 ?        S      0:00 sshd: me@pts/1
    167 pts/1    Ss     0:00 -bash
    198 pts/1    R+     0:00 ps ax
```

You can also run the command being used by `flask-batman-originators-server.py` while ssh'd in: `sudo batctl bat0 originators_json`:

```
me@node-1:~$ sudo batctl bat0 originators_json
[{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:03","last_seen_msecs":267,"neigh_address":"02:02:00:00:00:02","tq":221},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:03","best":true,"last_seen_msecs":267,"neigh_address":"02:02:00:00:00:03","tq":234},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:02","last_seen_msecs":307,"neigh_address":"02:02:00:00:00:03","tq":208},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:02","best":true,"last_seen_msecs":307,"neigh_address":"02:02:00:00:00:02","tq":251}]
```

**Comment by James-Sloop** [comment]
I have used ssh to get into node-1 and it seems you are right, flask is not running.

![image](https://github.com/adjacentlink/emane-guide/assets/100043766/d3e29d17-e3c7-44e3-8370-509481dc4170)

What am I able to do it fix this?

Here is my output from running ```sudo batctl bat0 originators_json```:
```[{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:03","last_seen_msecs":272,"neigh_address":"02:02:00:00:00:02","tq":225},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:03","best":true,"last_seen_msecs":272,"neigh_address":"02:02:00:00:00:03","tq":231},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:02","last_seen_msecs":168,"neigh_address":"02:02:00:00:00:03","tq":201},{"hard_ifindex":4,"hard_ifname":"emane0","orig_address":"02:02:00:00:00:02","best":true,"last_seen_msecs":168,"neigh_address":"02:02:00:00:00:02","tq":255}]```

**Comment by sgalgano** [comment]
Do you have a log file for `flask-batman-originators-server.py`: `emane-guide/examples/ieee80211abg-01/persist/node-1/var/log/flask-batman-originators-server.log`

```
$ head -n 20 persist/node-1/var/log/flask-batman-originators-server.log
 * Serving Flask app 'flask-batman-originators-server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://127.0.0.1:5001
Press CTRL+C to quit
10.99.0.100 - - [26/Jan/2024 14:15:34] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:15:40] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:15:46] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:15:52] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:15:58] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:04] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:10] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:16] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:22] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:28] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:34] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:40] "GET / HTTP/1.1" 200 -
10.99.0.100 - - [26/Jan/2024 14:16:46] "GET / HTTP/1.1" 200 -
```

**Comment by James-Sloop** [comment]
I do have a log file. It seems like it cannot detect flask but I have confirmed it is installed. Could it be an issue with the flask version or something else?

```
jcsloop@1311-2022-96:~/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/log$ head -n 20 flask-batman-originators-server.log 
Traceback (most recent call last):
  File "/home/hume-users/jcsloop/dev/emane-guide/examples/ieee80211abg-01/../scripts/flask-batman-originators-server.py", line 34, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

jcsloop@1311-2022-96:~/dev/emane-guide/examples/ieee80211abg-01/persist/node-1/var/log$ pip show flask
Name: Flask
Version: 3.0.1
Summary: A simple framework for building complex web applications.
Home-page: 
Author: 
Author-email: 
License: 
Location: /home/hume-users/jcsloop/.local/lib/python3.10/site-packages
Requires: blinker, click, itsdangerous, Jinja2, Werkzeug
Required-by: 
```

**Comment by sgalgano** [comment]
I would try installing flask using the distribution repo: `sudo apt-get install python3-flask`

**Comment by James-Sloop** [comment]
That was the problem. Thank you so much, the example is working now.
